### ISSUE TITLE
epic: finalize physical system

### ISSUE THREAD

**Issue by paul-bokelman** [paul-bokelman/prs#17]
## Description

Refine the physical system so it looks like a finished product.

## Tasks
- [ ] 3d print or laser print casing
- [ ] paint?
- [ ] connectivity LEDS
- [ ] standalone power supply
- [ ] power button
- [ ] replacement of current buttons

**Comment by paul-bokelman** [comment]
Currently pausing due to school finals and waiting for parts shipment.
